# Generated by Django 4.2.1 on 2023-06-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
